#ifndef OSGEARTH_EARTH_PLUGIN_SERIALIZER_OSGEARTHUTILLIBRARYNAME_H
#define OSGEARTH_EARTH_PLUGIN_SERIALIZER_OSGEARTHUTILLIBRARYNAME_H 1

#ifdef _DEBUG
#define LIBNAME_UTIL "@LIBNAME_UTIL_DEBUG@"
#else // _DEBUG
#  ifdef _MINSIZEREL
#    define LIBNAME_UTIL "@LIBNAME_UTIL_MINSIZEREL@"
#  else // _MINSIZEREL
#    ifdef _RELWITHDEBINFO
#      define LIBNAME_UTIL "@LIBNAME_UTIL_RELWITHDEBINFO@"
#    else // _RELWITHDEBINFO
#      define LIBNAME_UTIL "@LIBNAME_UTIL_RELEASE@"
#    endif // _RELWITHDEBINFO
#  endif // _MINSIZEREL
#endif // _DEBUG

#endif // OSGEARTH_EARTH_PLUGIN_SERIALIZER_OSGEARTHUTILLIBRARYNAME_H
